project:
  type: book

book:
  title: "The {targets} R package user manual"
  author: "Will Landau"
  page-footer: "How to get help: <https://books.ropensci.org/targets/help.html><br>Copyright 2022, Eli Lilly and Company" 
  chapters:
    - index.qmd
    - walkthrough.qmd
    - help.qmd
    - debugging.qmd
    - performance.qmd
    - functions.qmd
    - targets.qmd
    - packages.qmd
    - projects.qmd
    - data.qmd
    - literate-programming.qmd
    - dynamic.qmd
    - static.qmd
    - hpc.qmd
    - drake.qmd
    - markdown.qmd

format:
  html:
    theme: cosmo
