project:
  type: book

book:
  title: "The {targets} R package user manual"
  author: "Will Landau"
  page-footer: "How to get help: <https://books.ropensci.org/targets/help.html><br>Copyright 2022, Eli Lilly and Company" 
  chapters:
    - index.qmd
    - part: "How to use {targets}"
      chapters:
        - walkthrough.qmd
        - help.qmd
        - debugging.qmd
    - part: "Concepts / best practices"
      chapters:
        - functions.qmd
        - targets.qmd
        - packages.qmd
        - projects.qmd
    - part: "Data and files"
      chapters:
        - data.qmd
        - literate-programming.qmd
    - part: "Heavy workloads"
      chapters:
      - crew.qmd
      - performance.qmd
    - part: "Branching"
      chapters:
        - dynamic.qmd
        - static.qmd
  appendices:
    - drake.qmd
    - markdown.qmd

format:
  html:
    theme: cosmo
